refactor: Added the difference between working of finetuning vs transfer learning
premAI-io/state-of-open-source-ai pull request #75
Opened 2023-10-07 11:18 UTC by Anindyadeep

Since the finetuning page has concepts for both images and text. For texts fine-tuning term is commonly used but for images, sometimes people confuses the differences between the two.

# Review checklist

> Don't worry about satisfying all items, it's fine to open a (draft) PR.

- [ ] chapter content
  + [ ] only one top-level `# h1-Title`
  + [ ] summary (e.g. table or TL;DR overview), no need for an explicit `## Summary/Introduction` title or equivalent
  + [ ] main content focus: recent developments in open source AI
    + general context/background (brief)
    + current pros/cons
    + in-depth insights (not yet widely known)
  + [ ] likely `## Future` developments
  + [ ] end with `{{ comments }}`
- [ ] appropriate citations
  + [ ] BibTeX references
  + [ ] Glossary terms
  + [ ] cross-references (figures/chapters)
  + [ ] (if `new-chapter.md`), add `_toc.yml` entry & `index.md` table row
  + [ ] If CI URL checks have false-positives, append to `_config.yml:sphinx.config.linkcheck*`
- [ ] images & data not committed to this repo (e.g. use https://github.com/premAI-io/static.premai.io instead)

2023-10-07 11:19 UTC, Anindyadeep commented
The first commit is only for addressing the difference between the two. I will either add more commit or may be a different PR for Parameter efficient Finetuning methods.

2023-10-13 17:02 UTC, casperdcl requested changes
> Transfer learning can be applied on if the dataset (the one which we will be used in transfer learning) size is [large].

and

> Finetuning approach is often used when the dataset (that will be used for finetuning) is scarce.

are you sure it's not the other way around? transfer learning = mostly frozen, few unfrozen layers to train on minimal data, right? Meanwhile full fine-tuning is like retraining from scratch with a "good" weight initialisation, lots of unfrozen (trainable) weights, lots of data needed?

2023-10-13 17:02 UTC, casperdcl commented on fine-tuning.md
> +The key is that here the original weights of the pre-trained model remains unchanged and will not be trained (hence the term freezed). We train the new set of layers appeneded on the top of the pretr
are you sure?

2023-10-13 17:02 UTC, casperdcl commented on fine-tuning.md
> +Finetuning approach is often used when the dataset (that will be used for finetuning) is scarce. And in that case, we need to train parts of the model (or sometimes the whole model) to adapt on the t
are you sure?

2023-10-18 16:21 UTC, Anindyadeep commented
Hi @casperdcl, I am closing this PR. Because I am starting to contribute through my forked repo from now onwards.

2023-10-18 16:21 UTC, closed without merging